title: Heapnautic
logo: /assets/img/gabimaru.jpg
email: 8824348@gmail.com
description:
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: Home
    icon: <i class="fa-solid fa-home specific-icon" style="font-size: 15px;"></i>
    link: https://heapno.github.io/
  - name: Blog
    icon: <i class="fa-solid fa-file-code"></i>
    link: https://heapno.github.io/blog
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/dean-erlich-978008166
  - name: CV
    icon: <i class="fa-solid fa-file-lines"></i>
    link: https://heapno.github.io/cv.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Heapno

navigation:
  
